ControlWork1/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlWork1.Models
{
    public class Course : Entity
    {
        public string Name { get; set; }

        public ICollection<StudentCourses> StudentCourses { get; set; }
        public Course()
        {
            StudentCourses = new List<StudentCourses>();
        }
    }
}

ControlWork1/Models/Entity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlWork1.Models
{
    public class Entity
    {
        public int Id { get; set; }
    }
}

ControlWork1/Models/ErrorViewModel.cs
using System;

namespace ControlWork1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControlWork1/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlWork1.Models
{
    public class Student : Entity
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public ICollection<StudentCourses> StudentCourses { get; set; }
        public Student()
        {
            StudentCourses = new List<StudentCourses>();
        }
    }
}

ControlWork1/Models/StudentCourses.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlWork1.Models
{
    public class StudentCourses: Entity
    {
        public Student Student { get; set; }
        public int StudentId { get; set; }
        public Course Course { get; set; }
        public int CourseId { get; set; }
    }
}

ControlWork1/Models/StudentWithCourses.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlWork1.Models
{
    public class StudentWithCourses
    {
        public Student Student { get; set; }
        public List<Course> BaseCourses{ get; set; }
        public List<StudentCourses> Courses { get; set; }
    }
}

ControlWork1/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ControlWork1.Data.Repositories.Contracts;
using ControlWork1.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControlWork1.Controllers
{
    public class CourseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CourseController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Course> courses = _unitOfWork.CourseRepository.GetAll().ToList();
            return View(courses);
        }

        public IActionResult Create(int id)
        {
            if (id == 0)
            {
                return View();
            }

            Course course = _unitOfWork.CourseRepository.GetById(id);
            return View(course);
        }
        public IActionResult CreateOrUpdate(Course course)
        {
            _unitOfWork.CourseRepository.Add(course);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Course result = _unitOfWork.CourseRepository.GetById(id);
            return View(result);
        }

        public IActionResult DeleteItem(Course course)
        {
            _unitOfWork.CourseRepository.Delete(course);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Course course = _unitOfWork.CourseRepository.GetById(id);
            return View(course);
        }
    }
}

ControlWork1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ControlWork1.Models;

namespace ControlWork1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControlWork1/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ControlWork1.Data.Repositories.Contracts;
using ControlWork1.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControlWork1.Controllers
{
    public class StudentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public StudentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Student> students = _unitOfWork.StudentRepository.GetAll().ToList();
            return View(students);
        }
        public IActionResult Create(int id)
        {
            if (id == 0)
            {
                return View();
            }

            Student student = _unitOfWork.StudentRepository.GetById(id);
            return View(student);

        }
        public IActionResult CreateOrUpdate(Student student)
        {
            _unitOfWork.StudentRepository.Add(student);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Student student = _unitOfWork.StudentRepository.GetById(id);
            return View(student);
        }

        public IActionResult DeleteItem(Student student)
        {
            _unitOfWork.StudentRepository.Delete(student);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            StudentWithCourses model = new StudentWithCourses();
            Student student = _unitOfWork.StudentRepository.GetById(id);
            List<Course> baseCourses = _unitOfWork.CourseRepository.GetAll().ToList();
            List<StudentCourses> courses = _unitOfWork.StudenCoursesRepository.GetStudentCourses(id).ToList();
            model.Student = student;
            model.Courses = courses;
            model.BaseCourses = baseCourses;
            return View(model);
        }

        public IActionResult AddToCourse(int studentId, int courseId)
        {
            if (courseId == 0)
            {
                return RedirectToAction("Details", new { id = studentId });
            }
            StudentCourses courses = new StudentCourses();
            Student student = _unitOfWork.StudentRepository.GetById(studentId);
            Course course = _unitOfWork.CourseRepository.GetById(courseId);
            courses.Course = course;
            courses.CourseId = courseId;
            courses.Student = student;
            courses.StudentId = studentId;
            _unitOfWork.StudenCoursesRepository.Add(courses);
            if (!_unitOfWork.StudenCoursesRepository.IsExist(studentId, courseId))
            {
                _unitOfWork.Save();
            }
            else
            {
                _unitOfWork.RejectChanges();
            }
            return RedirectToAction("Details", new {id = studentId});
        }

        public IActionResult RemoveFromCourse(int studentId, int courseId)
        {
            if (courseId == 0)
            {
                return RedirectToAction("Details", new { id = studentId });
            }
            StudentCourses courses = new StudentCourses();
            Student student = _unitOfWork.StudentRepository.GetById(studentId);
            Course course = _unitOfWork.CourseRepository.GetById(courseId);
            courses.Course = course;
            courses.CourseId = courseId;
            courses.Student = student;
            courses.StudentId = studentId;
            _unitOfWork.StudenCoursesRepository.Delete(courses);
            _unitOfWork.Save();
            return RedirectToAction("Details", new { id = studentId });
        }
    }
}

ControlWork1/Views/Course/Create.cshtml
@model ControlWork1.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControlWork1/Views/Course/Delete.cshtml
@model ControlWork1.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControlWork1/Views/Course/Details.cshtml
@model ControlWork1.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ControlWork1/Views/Course/Index.cshtml
@model IEnumerable<ControlWork1.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Create", new { id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ControlWork1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><a asp-controller="Course">Курсы</a></h1>
    <h1 class="display-4"><a asp-controller="Student">Студенты</a></h1>
</div>

ControlWork1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlWork1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControlWork1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ControlWork1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ControlWork1/Views/Student/Create.cshtml
@model ControlWork1.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControlWork1/Views/Student/Delete.cshtml
@model ControlWork1.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControlWork1/Views/Student/Details.cshtml
@model ControlWork1.Models.StudentWithCourses

@{
    ViewData["Title"] = "Details";
}

<h1>Student</h1>
<div>
    <span>@Model.Student.FirstName</span>
    <span>@Model.Student.LastName</span>
</div>

<table class="table">
    <thead>
    <tr>
        <th>
            <i>Id</i>
        </th>
        <th>
            <i>Название курса</i>
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Courses) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    </tbody>
</table>

<form asp-action="AddToCourse">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="form-group">
            <div class="form-group">
                <label asp-for="BaseCourses" class="control-label"></label>
                <select class="form-control"
                        asp-for="BaseCourses"
                        asp-items="@(new SelectList(Model.BaseCourses,"Id","Name" ))" name="courseId">
                </select>
                <span asp-validation-for="BaseCourses" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input asp-for="@Model.Student.Id" name="studentId" type="hidden" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Записать на курс" class="btn btn-primary" />
    </div>
</form>

<form asp-action="RemoveFromCourse">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="form-group">
            <div class="form-group">
                <label asp-for="Courses" class="control-label"></label>
                <select class="form-control"
                        asp-for="Courses"
                        asp-items="@(new SelectList(Model.Courses.Select(x => new KeyValuePair<string, string>(x.CourseId.ToString(), x.Course.Name)), "Key", "Value"))" name="courseId"></select>
                <span asp-validation-for="Courses" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input asp-for="@Model.Student.Id" name="studentId" type="hidden" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Удалить с курса" class="btn btn-primary" />
    </div>
</form>

ControlWork1/Views/Student/Index.cshtml
@model IEnumerable<ControlWork1.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Create", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>